### ISSUE TITLE
can you fix this ?

### ISSUE THREAD

**Issue by amangasas** [Mee12345/GWater-V3#14]
![image](https://user-images.githubusercontent.com/127668645/224546043-03522993-dbbb-40f2-aff7-69e0788a3a7b.png)

**Comment by amangasas** [comment]
![image](https://user-images.githubusercontent.com/127668645/224546069-6fc2db7a-9d44-4dc2-8fdb-00d34d03c371.png)

**Comment by john123903** [comment]
Use the gmod modules zip

**Comment by amangasas** [comment]
but i dont have that folder after update

**Comment by john123903** [comment]
Just download the zip file in gwater module GitHub.

**Comment by john123903** [comment]
wait… YOU DONT HAVE A BIN FOLDER

**Comment by john123903** [comment]
create a bin folder.

**Comment by amangasas** [comment]
its not working

**Comment by john123903** [comment]
did you create a bin folder?

**Comment by amangasas** [comment]
yes

**Comment by amangasas** [comment]
how can i fix this ???????????

**Comment by amangasas** [comment]
i need vrmod or this not working but its working

**Comment by amangasas** [comment]
yeah its working and its cool
