### ISSUE TITLE
GWater not working

### ISSUE THREAD

**Issue by JermainPZ** [Mee12345/GWater-V3#5]
i installed the mod, installed the github and did everything the instructions told me to. yet when i choose a map and try to play the game crashes
i removed the bin folder inside the lua folder containing the gmcl dlls
the game didn't crash this time but the water isn't working correctly
i put the dlls back in and the game crashes
how the heck do i fix this??

**Comment by AtaKanK4467** [comment]
same happens to me.

**Comment by Mee12345** [comment]
this means your gpu isn't powerful enough to run nvidia flex
https://gameworksdocs.nvidia.com/FleX/1.2/lib_docs/index.html#requirements

however.. if your gpu is actually powerful enough then something must be messed up in our code.. maybe elaborate more on how you installed it?
