### ISSUE TITLE
Is there a Linux version?

### ISSUE THREAD

**Issue by OhaDerErste** [Mee12345/GWater-V3#7]

**Comment by Derpius** [comment]
Nope, and both him and andrew don’t know cross compiling and refuse to listen to help

**Comment by Mee12345** [comment]
yeah we literally don't know how to compile for linux / other operating systems, flex does have compatibility with linux though, so if you do or someone knows how to compile for linux then help would be appreciated..

**Comment by Derpius** [comment]
That’s funny, cause whenever anyone tries to help you, you get really defensive and angry with the other person


![](https://cdn.discordapp.com/attachments/800234485115256864/932806637159321640/unknown.png)

![](https://media.discordapp.net/attachments/826587447236100137/932059786239942666/unknown.png)
Regarding this code (which, to anyone who knows more than basic C++, is obviously wrong)
![](https://media.discordapp.net/attachments/826587447236100137/932058886750470154/unknown.png)

**Comment by Mee12345** [comment]
I did prints man, works fine for me

**Comment by Mee12345** [comment]
pretty sure compiling for other operating systems is a process that needs different software to compile it, not different code

**Comment by Derpius** [comment]
Platform dependant code and libraries @Mee12345, as well as different standards for the language on different platforms

Also me, Vurv, and PotatoOS have all explained in great detail why that snippet wont work, hell even andrew apparently said it didn't look like it would work, so you don't even need to listen to me to know that doing an equality check between the return value of `ILuaBase::GetNumber` and an enum is not actually type checking

**Comment by Mee12345** [comment]
so wait, then why does it work?

**Comment by Mee12345** [comment]
ah I see, Type::Nil is equal to 0 kind of like NULL, and when GetNumber fails it RETURNS 0
so it works as intended!

**Comment by Derpius** [comment]
It only works with a subset of possible input values, as people have already said, but I'll lay it out for you again here:

https://github.com/Facepunch/gmod-module-base/blob/development/include/GarrysMod/Lua/Types.h#L19
This is an unscoped enum (just wrapped in a namespace to require using `Type::Nil` instead of just `Nil`), meaning it will implicitly cast to its underlying datatype without issue (compared to `enum class EnumName` which will not implicitly cast)  
Running http://cpp.sh/9ypby will print `True` because of this  

Now guess what, you're getting that number from an argument passed to a function in the global table, if I pass `0` to that 6th argument, it will think the type is incorrect, even though it's not, and `num` will be `1`, not `0` which is what I passed

**Comment by Mee12345** [comment]
this is an intended thing, flex particles should not have 0 mass

**Comment by Derpius** [comment]
well you never check for negatives there so either you do absolutely no input validation, or you're checking if it's > 0 later on, meaning your terrible practice for type checking is redundant anyway

**Comment by Mee12345** [comment]
¯\_(ツ)_/¯ seems like a clean solution to me

**Comment by Derpius** [comment]
ah yes, how clean, when functions already exist to perform real type checking, and you're not even validating that it's positive

**Comment by Zubbbz** [comment]
"jackass"

**Comment by Mee12345** [comment]
alright someone figured out how to make linux work with it, apparently you can install something called “proton” and then add the dlls manually with the zip.. so I guess theres ur answer

**Comment by Derpius** [comment]
Oh my god you used **proton**, a library for emulating windows **games** on linux, instead of compiling natively

**Comment by jornmann** [comment]
I know it's been a while since this issue was made and closed, but I think this issue should be kept open in case someone else is able to compile GWater for Linux.
